---
# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Configured to align with Prettier. Prettier handles all formatting (indentation,
# spacing, line wrapping); Markdownlint handles style/syntax validity (tildes, etc).

# Default state for all rules
default: true

# --- Rules to Disable (Handled by Prettier) ---
# MD004: Unordered list style (Prettier enforces this)
MD004: false
# MD005: Inconsistent indentation (Prettier enforces this)
MD005: false
# MD007: Unordered list indentation
# Conflict: Prettier aligns nested lists with parent text (e.g. 3 spaces for "1. "),
# while MD007 strictly enforces a fixed number (2).
MD007: false
# MD009: Trailing spaces (Prettier removes these)
MD009: false
# MD010: Hard tabs (Prettier enforces spaces)
MD010: false
# MD024: Allow duplicate headings (for CHANGELOG.md)
MD024: false
# MD027: Multiple spaces after blockquote symbol (Prettier handles this)
MD027: false
# MD030: Spaces after list markers (Prettier handles this)
MD030: false
# MD032: Lists should be surrounded by blank lines (Prettier handles this)
MD032: false
# MD033: Inline HTML (Allowed for complex diagrams/badges)
MD033: false

# --- Rules to Configure ---

# MD013: Set line length to 120
# Disable checks for tables/code blocks as they cannot be wrapped easily.
# Note: Prettier with 'proseWrap: always' will enforce this for regular text.
MD013:
  line_length: 120
  tables: false
  code_blocks: false

# MD035: Set horizontal rule style to the 70-character underscore string.
MD035:
  style: "______________________________________________________________________"

# MD046: Code block style
# Enforce tildes (~~~) to prevent issues with AI response parsing/nesting
MD046:
  style: "tilde"

# MD049: Set emphasis style to UNDERSCORE (to match Prettier default)
MD049:
  style: underscore
