# .prettierrc.yaml
# Aligns frontend formatting with Python/Ruff standards where possible

# Use 4 spaces to match Python indentation (Consistency > Standard JS style)
tabWidth: 4
useTabs: false

# Print width matches Ruff's line-length (120)
printWidth: 120

# Formatting preferences
semi: true
singleQuote: false
trailingComma: "es5"
bracketSpacing: true
arrowParens: "always"
endOfLine: "lf"

# MANDATORY: Forces Prettier to wrap Markdown text at 'printWidth' (120)
# Default is "preserve", which ignores line length in Markdown.
proseWrap: "always"

# Override for specific file types if necessary
overrides:
  - files: "*.yml"
    options:
      tabWidth: 2
  - files: "*.yaml"
    options:
      tabWidth: 2
  - files: "*.json"
    options:
      tabWidth: 4
  # Markdown overrides to prevent conflict with markdownlint (MD007)
  # Prettier defaults to the global tabWidth (4), but standard Markdown uses 2.
  - files: "*.md"
    options:
      tabWidth: 2
